name: Add hacks
description: Use this in case of finding wrong solutions being accepted and wanting to hack it.
body:
  - type: input
    attributes:
      label: Problem ID
      placeholder: 'e.g. 1C'
    validations:
      required: true
  - type: input
    attributes:
      label: Hacked Submission ID(s)
      placeholder: 'e.g. 896'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input/Generator
      placeholder: |
        *Example 1:*
        
        ```plain
        2 2 1 1
        1 1
        1 1
        ```
        
        *Example 2:*
        
        ```cpp
        #include <bits/stdc++.h>
        using namespace std;
        int main()
        {
        	freopen("45.in", "w", stdout);
        	puts("2 2 1 1");
        	puts("1 1");
        	puts("1 1");
        	return 0;
        }
        ```
    validations:
      required: true
