type: objective
answers:
  '1':
    - C
    - 2
  '2':
    - A
    - 2
  '3':
    - B
    - 2
  '4':
    - C
    - 2
  '5':
    - C
    - 2
  '6':
    - A
    - 2
  '7':
    - D
    - 2
  '8':
    - D
    - 2
  '9':
    - A
    - 2
  '10':
    - B
    - 2
  '11':
    - B
    - 2
  '12':
    - C
    - 2
  '13':
    - B
    - 2
  '14':
    - A
    - 2
  '15':
    - D
    - 2
  '16':
    - A
    - 1
  '17':
    - B
    - 1
  '18':
    - B
    - 1
  '19':
    - D
    - 3
  '20':
    - C
    - 3
  '21':
    - D
    - 4
  '22':
    - B
    - 1
  '23':
    - A
    - 1
  '24':
    - A
    - 1
  '25':
    - A
    - 3
  '26':
    - A
    - 3
  '27':
    - D
    - 4
  '28':
    - A
    - 1
  '29':
    - A
    - 1
  '30':
    - A
    - 1
  '31':
    - B
    - 3
  '32':
    - B
    - 3
  '33':
    - C
    - 5
  '34':
    - B
    - 3
  '35':
    - D
    - 3
  '36':
    - D
    - 3
  '37':
    - A
    - 3
  '38':
    - C
    - 3
  '39':
    - C
    - 3
  '40':
    - D
    - 3
  '41':
    - B
    - 3
  '42':
    - A
    - 3
  '43':
    - B
    - 3
