type: default
time: 2000ms
memory: 8MB
filename: median
subtasks:
  - score: 0
    id: 0
    type: sum
    cases:
      - input: 1.in
        output: 1.out
      - input: 2.in
        output: 2.out
      - input: 3.in
        output: 3.out
      - input: 4.in
        output: 4.out
      - input: 5.in
        output: 5.out
  - score: 50
    if:
      - 0
    id: 1
    type: min
    cases:
      - input: 6.in
        output: 6.out
      - input: 7.in
        output: 7.out
      - input: 8.in
        output: 8.out
      - input: 9.in
        output: 9.out
      - input: 10.in
        output: 10.out
  - score: 50
    if:
      - 0
      - 1
    id: 2
    type: min
    cases:
      - input: 11.in
        output: 11.out
      - input: 12.in
        output: 12.out
      - input: 13.in
        output: 13.out
      - input: 14.in
        output: 14.out
      - input: 15.in
        output: 15.out
