type: default
memory: 512MB
filename: league
subtasks:
  - score: 25
    id: 1
    type: min
    cases:
      - input: 1.in
        output: 1.out
      - input: 2.in
        output: 2.out
  - score: 25
    if:
      - 1
    id: 2
    type: min
    cases:
      - input: 3.in
        output: 3.out
      - input: 4.in
        output: 4.out
  - score: 25
    if:
      - 1
      - 2
    id: 3
    type: min
    cases:
      - input: 5.in
        output: 5.out
      - input: 6.in
        output: 6.out
      - input: 7.in
        output: 7.out
  - score: 25
    if:
      - 1
      - 2
      - 3
    id: 4
    type: min
    cases:
      - input: 8.in
        output: 8.out
      - input: 9.in
        output: 9.out
      - input: 10.in
        output: 10.out
