type: objective
answers:
  '1':
    - A
    - 10
  '2':
    - D
    - 10
  '3':
    - B
    - 10
  '4':
    - B
    - 10
  '5':
    - C
    - 10
  '6':
    - - B
      - C
    - 10
  '7':
    - - A
      - B
    - 10
  '8':
    - '10101011'
    - 10
  '9':
    - '0'
    - 10
  '10':
    - cirrationaler
    - 10
